
broadcast = adb shell am broadcast -a
debug     = -e debug yes

play      = $(broadcast) org.smblott.intentradio.PLAY $(debug)
stop      = $(broadcast) org.smblott.intentradio.STOP
pause     = $(broadcast) org.smblott.intentradio.PAUSE
restart   = $(broadcast) org.smblott.intentradio.RESTART
click     = $(broadcast) org.smblott.intentradio.CLICK

play:
	$(play)

stop:
	$(stop)

r4:
	$(play) -e url http://www.bbc.co.uk/mediaselector/playlists/hls/radio/nonuk/lo/ak/bbc_radio_fourfm.m3u8 -e name "BBC Radio 4 (Fast)"

# This blocks for quite some time, and cannot be cancelled until buffering has
# completed; Android bug.
r4aac:
	$(play) -e url http://www.bbc.co.uk/radio/listen/live/r4_heaacv2.pls -e name "BBC Radio 4"

ufm:
	$(play) -e url http://192.168.3.3/cgi-bin/sc/wav -e name "Elsa Sound Card"

wnyc:
	$(play) -e url http://www.wnyc.org/stream/fm.pls -e name "WNYC"

newstalk:
	$(play) -e url http://communicorp.mp3.miisolutions.net:8000/communicorp/Newstalk_low.m3u -e name "Newstalk"

lyric:
	$(play) -e url http://icecast2.rte.ie/lyric -e name "RTE Lyric FM"

shoutcast:
	$(play) -e url 'http://yp.shoutcast.com/sbin/tunein-station.pls?id=230816' -e name "Shoutcast"

file:
	$(play) -e url file:///sdcard/x.mp3 -e name "/sdcard/x/mp3"

pause:
	$(pause)

restart:
	$(restart)

click:
	$(click)

.PHONY: play stop r4 r4aac ufm wnyc newstalk lyric shoutcast file pause restart click

wien:
	# $(play) -e url 'http://mp3stream2.apasf.apa.at:8000/listen.pls' -e name "Wien"
	# $(play) -e url '' -e name "Wien"
	# $(play) -e url 'http://mp3stream3.apasf.apa.at:8000/listen.pls' -e name "Oe 1"
	# $(play) -e url 'http://mp3stream1.apasf.apa.at:8000/listen.pls' -e name "FM4"
	# $(play) -e url 'http://amber.streamguys.com:4020/live' -e name "WEAA"
	$(play) -e url 'http://live.str3am.com:2410/wypr.m3u' -e name "WYPR"

