
root = ../../../../..

debug install release clean google google-release:
	cd $(root) && $(MAKE) $@

.PHONY: debug install release clean google google-release

# Use path (again) so that completion works.
#
include ../../../../../Makefile.test

