
root = ../../../../..

debug install release clean:
	cd $(root) && $(MAKE) $@

.PHONY: debug install release clean

# Use path (again) so that completion works.
#
include ../../../../../Makefile.test

